// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | FrequentlyAskedQuestionsSlice
  | CountdownSlice
  | SliderSlice
  | SplitImageTextSlice
  | TextBlockSlice
  | DividerSlice
  | ModalSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *AccordionImage → Primary*
 */
export interface AccordionImageSliceDefaultPrimary {
  /**
   * Title field in *AccordionImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *AccordionImage → Items*
 */
export interface AccordionImageSliceDefaultItem {
  /**
   * ItemTitle field in *AccordionImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_image.items[].itemtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  itemtitle: prismic.KeyTextField;

  /**
   * Content field in *AccordionImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_image.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *AccordionImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AccordionImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionImageSliceDefaultPrimary>,
  Simplify<AccordionImageSliceDefaultItem>
>;

/**
 * Slice variation for *AccordionImage*
 */
type AccordionImageSliceVariation = AccordionImageSliceDefault;

/**
 * AccordionImage Shared Slice
 *
 * - **API ID**: `accordion_image`
 * - **Description**: AccordionImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionImageSlice = prismic.SharedSlice<
  "accordion_image",
  AccordionImageSliceVariation
>;

/**
 * Primary content in *Countdown → Primary*
 */
export interface CountdownSliceDefaultPrimary {
  /**
   * Title field in *Countdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: countdown.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Target Date field in *Countdown → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: countdown.primary.targetDate
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  targetDate: prismic.DateField;
}

/**
 * Default variation for Countdown Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountdownSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CountdownSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Countdown*
 */
type CountdownSliceVariation = CountdownSliceDefault;

/**
 * Countdown Shared Slice
 *
 * - **API ID**: `countdown`
 * - **Description**: Countdown
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountdownSlice = prismic.SharedSlice<
  "countdown",
  CountdownSliceVariation
>;

/**
 * Primary content in *Divider → Primary*
 */
export interface DividerSliceDefaultPrimary {
  /**
   * Background Color field in *Divider → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: divider.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  backgroundColor: prismic.ColorField;

  /**
   * Thickness field in *Divider → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: divider.primary.thickness
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  thickness: prismic.NumberField;

  /**
   * Space Above field in *Divider → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: divider.primary.spaceAbove
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  spaceAbove: prismic.NumberField;

  /**
   * Space Below field in *Divider → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: divider.primary.spaceBelow
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  spaceBelow: prismic.NumberField;
}

/**
 * Default variation for Divider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DividerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Divider*
 */
type DividerSliceVariation = DividerSliceDefault;

/**
 * Divider Shared Slice
 *
 * - **API ID**: `divider`
 * - **Description**: Divider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSlice = prismic.SharedSlice<
  "divider",
  DividerSliceVariation
>;

/**
 * Primary content in *FrequentlyAskedQuestions → Primary*
 */
export interface FrequentlyAskedQuestionsSliceDefaultPrimary {
  /**
   * Title field in *FrequentlyAskedQuestions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *FrequentlyAskedQuestions → Items*
 */
export interface FrequentlyAskedQuestionsSliceDefaultItem {
  /**
   * Title field in *FrequentlyAskedQuestions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *FrequentlyAskedQuestions → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for FrequentlyAskedQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrequentlyAskedQuestionsSliceDefaultPrimary>,
  Simplify<FrequentlyAskedQuestionsSliceDefaultItem>
>;

/**
 * Slice variation for *FrequentlyAskedQuestions*
 */
type FrequentlyAskedQuestionsSliceVariation =
  FrequentlyAskedQuestionsSliceDefault;

/**
 * FrequentlyAskedQuestions Shared Slice
 *
 * - **API ID**: `frequently_asked_questions`
 * - **Description**: FrequentlyAskedQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSlice = prismic.SharedSlice<
  "frequently_asked_questions",
  FrequentlyAskedQuestionsSliceVariation
>;

/**
 * Primary content in *Modal → Primary*
 */
export interface ModalSliceDefaultPrimary {
  /**
   * Tite Color field in *Modal → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.primary.titleColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  titleColor: prismic.ColorField;

  /**
   * Text Color field in *Modal → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.primary.textColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  textColor: prismic.ColorField;

  /**
   * Items Alignment field in *Modal → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.primary.itemsAlignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  itemsAlignment: prismic.SelectField<"start" | "center" | "end">;

  /**
   * Text Alignment field in *Modal → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.primary.textAlignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textAlignment: prismic.SelectField<"left" | "center" | "right" | "justify">;

  /**
   * Image Height (%) field in *Modal → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0 - 100
   * - **API ID Path**: modal.primary.imageHeight
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  imageHeight: prismic.NumberField;

  /**
   * Image Width (%) field in *Modal → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0 - 100
   * - **API ID Path**: modal.primary.imageWidth
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  imageWidth: prismic.NumberField;
}

/**
 * Primary content in *Modal → Items*
 */
export interface ModalSliceDefaultItem {
  /**
   * Image field in *Modal → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Modal → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Modal → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Label field in *Modal → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Modal Title field in *Modal → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].modalTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modalTitle: prismic.KeyTextField;

  /**
   * Modal Body field in *Modal → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].modalBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  modalBody: prismic.RichTextField;

  /**
   * Modal Image field in *Modal → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].modalImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  modalImage: prismic.ImageField<never>;

  /**
   * Modal Image Width (%) field in *Modal → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: modal.items[].modalImageWidth
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  modalImageWidth: prismic.NumberField;
}

/**
 * Default variation for Modal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ModalSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ModalSliceDefaultPrimary>,
  Simplify<ModalSliceDefaultItem>
>;

/**
 * Slice variation for *Modal*
 */
type ModalSliceVariation = ModalSliceDefault;

/**
 * Modal Shared Slice
 *
 * - **API ID**: `modal`
 * - **Description**: Modal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ModalSlice = prismic.SharedSlice<"modal", ModalSliceVariation>;

/**
 * Primary content in *Slider → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Image Width (%) field in *Slider → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.primary.imageWidth
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  imageWidth: prismic.NumberField;
}

/**
 * Primary content in *Slider → Items*
 */
export interface SliderSliceDefaultItem {
  /**
   * Image field in *Slider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  Simplify<SliderSliceDefaultItem>
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *SplitImageText → Primary*
 */
export interface SplitImageTextSliceDefaultPrimary {
  /**
   * Image field in *SplitImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *SplitImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Color field in *SplitImageText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  backgroundColor: prismic.ColorField;

  /**
   * Text Color field in *SplitImageText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.textColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  textColor: prismic.ColorField;

  /**
   * Text Alignment field in *SplitImageText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.textAlignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textAlignment: prismic.SelectField<"left" | "center" | "right" | "justify">;
}

/**
 * Default variation for SplitImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SplitImageText → Primary*
 */
export interface SplitImageTextSliceImageRigthPrimary {
  /**
   * Image field in *SplitImageText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *SplitImageText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Color field in *SplitImageText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  backgroundColor: prismic.ColorField;

  /**
   * Text Color field in *SplitImageText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.textColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  textColor: prismic.ColorField;

  /**
   * Text Alignment field in *SplitImageText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: split_image_text.primary.textAlignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textAlignment: prismic.SelectField<"left" | "center" | "right" | "justify">;
}

/**
 * ImageRigth variation for SplitImageText Slice
 *
 * - **API ID**: `imageRigth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitImageTextSliceImageRigth = prismic.SharedSliceVariation<
  "imageRigth",
  Simplify<SplitImageTextSliceImageRigthPrimary>,
  never
>;

/**
 * Slice variation for *SplitImageText*
 */
type SplitImageTextSliceVariation =
  | SplitImageTextSliceDefault
  | SplitImageTextSliceImageRigth;

/**
 * SplitImageText Shared Slice
 *
 * - **API ID**: `split_image_text`
 * - **Description**: SplitImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitImageTextSlice = prismic.SharedSlice<
  "split_image_text",
  SplitImageTextSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Text Color field in *TextBlock → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.textColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  textColor: prismic.ColorField;

  /**
   * Background Color field in *TextBlock → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.backgroundColor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  backgroundColor: prismic.ColorField;

  /**
   * Text Alignment field in *TextBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.textAlignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textAlignment: prismic.SelectField<"left" | "center" | "right" | "justify">;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionImageSlice,
      AccordionImageSliceDefaultPrimary,
      AccordionImageSliceDefaultItem,
      AccordionImageSliceVariation,
      AccordionImageSliceDefault,
      CountdownSlice,
      CountdownSliceDefaultPrimary,
      CountdownSliceVariation,
      CountdownSliceDefault,
      DividerSlice,
      DividerSliceDefaultPrimary,
      DividerSliceVariation,
      DividerSliceDefault,
      FrequentlyAskedQuestionsSlice,
      FrequentlyAskedQuestionsSliceDefaultPrimary,
      FrequentlyAskedQuestionsSliceDefaultItem,
      FrequentlyAskedQuestionsSliceVariation,
      FrequentlyAskedQuestionsSliceDefault,
      ModalSlice,
      ModalSliceDefaultPrimary,
      ModalSliceDefaultItem,
      ModalSliceVariation,
      ModalSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimary,
      SliderSliceDefaultItem,
      SliderSliceVariation,
      SliderSliceDefault,
      SplitImageTextSlice,
      SplitImageTextSliceDefaultPrimary,
      SplitImageTextSliceImageRigthPrimary,
      SplitImageTextSliceVariation,
      SplitImageTextSliceDefault,
      SplitImageTextSliceImageRigth,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
