// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_image: dynamic(() => import("./AccordionImage")),
  countdown: dynamic(() => import("./Countdown")),
  divider: dynamic(() => import("./Divider")),
  frequently_asked_questions: dynamic(
    () => import("./FrequentlyAskedQuestions"),
  ),
  modal: dynamic(() => import("./Modal")),
  slider: dynamic(() => import("./Slider")),
  split_image_text: dynamic(() => import("./SplitImageText")),
  text_block: dynamic(() => import("./TextBlock")),
};
